. "$HOME/.$USER-sh/config/p10k/init.zsh"
. "$HOME/.$USER-sh/config/omz/init.zsh"

# macOS
# if [ -x /usr/libexec/path_helper ]; then
#     eval `/usr/libexec/path_helper -s`
# fi

# load all files in $HOME/.$USER-sh/config/sh/
for sh in "$HOME"/".$USER-sh"/config/sh/*.sh
do
    . "$sh"
done

. "$HOME/.$USER-sh/config/p10k/config.zsh"
