. "$HOME/.$USER-sh/config/p10k/init.zsh"
. "$HOME/.$USER-sh/config/omz/init.zsh"

# macOS
# if [ -x /usr/libexec/path_helper ]; then
#     eval `/usr/libexec/path_helper -s`
# fi

. "$HOME/.$USER-sh/config/p10k/config.zsh"
