# source zsh-defer, used to defer execution of nvm init, jenv init, etc.
# [ -d "$HOME/.$USER-sh/softwares/zsh-defer" ] && . "$HOME/.$USER-sh/softwares/zsh-defer/zsh-defer.plugin.zsh"

. "$HOME/.$USER-sh/etc/sh/profile"

# skip sourcing of /etc/z{shrc,login,logout}
unsetopt global_rcs
