#
# oh-my-zsh

# source oh-my-zsh init file if directy exists
[ -d "$ZSH" ] && . "$HOME/.$USER-sh/etc/omz/init.zsh"

# source powerlevel10k init file if omz theme is powerlevel10k
[ "${ZSH_THEME#*powerlevel10k}" != "$ZSH_THEME" ] && . "$HOME/.$USER-sh/etc/p10k/init.zsh"


#
# misc zsh options

# if a glob (e.g. *.txt) has no match, pass the glob as-is to the command
# instead of printing error message
unsetopt nomatch

# do not require a leading . to match dot files
setopt glob_dots

# do not store commands starting with a space in history
setopt hist_ignore_space

# disable `you have new mail message'
unset mailcheck


#
# source any file in etc/sh/rc.d/

for file in "$HOME"/".$USER-sh"/etc/sh/rc.d/*
do
    . "$file"
done

#
# oh-my-zsh

# source powerlevel10k config file if omz theme is powerlevel10k
[ "${ZSH_THEME#*powerlevel10k}" != "$ZSH_THEME" ] && . "$HOME/.$USER-sh/etc/p10k/config.zsh"
