#
# powerlevel10k theme
[ -d "$HOME/.$USER-sh/softwares/powerlevel10k" ] && . "$HOME/.$USER-sh/etc/zsh/p10k/instant-prompt.zsh"


#
# zsh keyboard

# If we want to use terminfo capabilities with bindkey, we need to enable the
# `application mode' (aka keyboard_transmit) when zle starts, and then disable
# it when zle exists. The reason is that the terminfo descriptions are written
# for when the terminal is in application mode. Something like that.
#
# e.g. in normal mode, the up arrow key returns ^[[A, in app mode it returns
# ^[OA, the terminfo value for kcuu1 is ^[OA.
if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} ))
then
    function zle-line-init () {
        echoti smkx
    }

    function zle-line-finish () {
        echoti rmkx
    }

    zle -N zle-line-init
    zle -N zle-line-finish
else
    echo Application mode not supported >&2
fi

# vi keymap is used when setting VISUAL to vim, restore emacs keymap
bindkey -e

typeset -g -A key

[ -n "$terminfo[khome]" ] && key[Home]=$terminfo[khome]
[ -n "$terminfo[kend]" ] && key[End]=$terminfo[kend]
[ -n "$terminfo[kdch1]" ] && key[Delete]=$terminfo[kdch1]
[ -n "$terminfo[kcuu1]" ] && key[Up]=$terminfo[kcuu1]
[ -n "$terminfo[kcud1]" ] && key[Down]=$terminfo[kcud1]

[ -n ${key[Home]} ] && bindkey "${key[Home]}" beginning-of-line
[ -n ${key[End]} ] && bindkey "${key[End]}" end-of-line
[ -n ${key[Delete]} ] && bindkey "${key[Delete]}" delete-char

#
# zsh history

HISTFILE=${ZDOTDIR}/.zsh_history
SAVEHIST=10000000 # items to keep in histfile
HISTSIZE=10000000 # items from histfile to load into memory
setopt extended_history # write timestamp of command in histfile
setopt hist_ignore_space # don't record commands starting with a space
setopt hist_fcntl_lock # supposedly better performance
setopt hist_find_no_dups # don't show duplicates when searching history
setopt hist_ignore_dups # don't record command if it's duplicate from previous entry
setopt hist_reduce_blanks # remove superfluous blanks

# bind up/down arrows to history search
autoload -Uz up-line-or-beginning-search
autoload -Uz down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
[ -n ${key[Up]} ] && bindkey "${key[Up]}" up-line-or-beginning-search
[ -n ${key[Down]} ] && bindkey "${key[Down]}" down-line-or-beginning-search

# bind ctrl-space to show a menu of history items matching current line content
autoload -Uz history-beginning-search-menu
zle -N history-beginning-search-menu-end history-beginning-search-menu
bindkey '^ ' history-beginning-search-menu-end


#
# zsh autocompletion

# enable autocompletion
autoload -Uz compinit
compinit

# enable the arrow-key-driven ui
zstyle ':completion:*' menu select

# in-word autocompletion:
#   https://stackoverflow.com/a/68794830
#   https://stackoverflow.com/a/69014927
zstyle ':completion:*' matcher-list \
    'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' \
    '+r:|[._-]=* r:|=*' \
    '+l:|=*'

# disable completion of users for the ssh and scp command
zstyle ':completion:*:(ssh|scp):*' users

setopt no_list_ambiguous # do show menu after inserting unambiguous prefix
setopt list_packed # try to make completion list smaller


#
# zsh directory stack

setopt auto_pushd # push current directory visited on the stack
setopt pushd_ignore_dups # don't store duplicates in the stack
setopt pushd_silent # don't print the directory stack after pushd or popd


#
# zsh misc

# if a glob (e.g. *.txt) has no match, pass the glob as-is to the command
# instead of printing error message
setopt no_no_match

# do not require a leading . to match dot files
setopt glob_dots

# disable `you have new mail message'
unset MAILCHECK

# `/' also delimits words (for backward-kill-word, etc.)
autoload -Uz select-word-style
select-word-style bash


#
# source any file in etc/sh/rc.d/

for file in "$HOME"/".$USER-sh"/etc/sh/rc.d/*
do
    . "$file"
done
