#
# oh-my-zsh

# source oh-my-zsh init file if directy exists
[ -d "$ZSH" ] && . "$HOME/.$USER-sh/etc/omz/init.zsh"

# source powerlevel10k init file if omz theme is powerlevel10k
[ "${ZSH_THEME#*powerlevel10k}" != "$ZSH_THEME" ] && . "$HOME/.$USER-sh/etc/p10k/init.zsh"


#
# zsh keyboard

# vi keymap is used when setting VISUAL to vim, restore emacs keymap
bindkey -e

bindkey  "^[[H"   beginning-of-line # home key
bindkey  "^[[F"   end-of-line # end key
bindkey  "^[[3~"  delete-char # del key

# add values to key array for later use by bindkey
# typeset -g -A key
# [ -n "$terminfo[kcuu1]" ] && key[Up]=$terminfo[kcuu1]
# [ -n "$terminfo[kcud1]" ] && key[Down]=$terminfo[kcud1]


#
# zsh history

HISTFILE=${ZDOTDIR}/.zsh_history
SAVEHIST=10000000 # items to keep in histfile
HISTSIZE=10000000 # items from histfile to load into memory
setopt extended_history # write timestamp of command in histfile
setopt hist_ignore_space # don't record commands starting with a space
setopt hist_fcntl_lock # supposedly better performance
setopt hist_find_no_dups # don't show duplicates when searching history
setopt hist_ignore_dups # don't record command if it's duplicate from previous entry
setopt hist_reduce_blanks # remove superfluous blanks

# load history-search-end function from zshcontrib and bind up/down arrows to
# its two widgets
autoload -Uz history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey '^[[A' history-beginning-search-backward-end
bindkey '^[[B' history-beginning-search-forward-end

# bind ctrl space to show a menu of history items matching current line content
autoload -Uz history-beginning-search-menu
zle -N history-beginning-search-menu-end history-beginning-search-menu
bindkey '^ ' history-beginning-search-menu-end


#
# zsh autocompletion

# enable autocompletion
autoload -Uz compinit
compinit

# enable the arrow-key-driven ui
zstyle ':completion:*' menu select

# in-word autocompletion: https://stackoverflow.com/a/68794830
zstyle ':completion:*' matcher-list \
    'm:{[:lower:]}={[:upper:]}' \
    '+r:|[._-]=* r:|=*' \
    '+l:|=*'

# disable completion of users for the ssh and scp command
zstyle ':completion:*:(ssh|scp):*' users

setopt no_list_ambiguous # do show menu after inserting unambiguous prefix
setopt list_packed # try to make completion list smaller


#
# zsh directory stack

setopt auto_pushd # push current directory visited on the stack
setopt pushd_ignore_dups # don't store duplicates in the stack
setopt pushd_silent # don't print the directory stack after pushd or popd


#
# zsh misc

# if a glob (e.g. *.txt) has no match, pass the glob as-is to the command
# instead of printing error message
setopt no_no_match

# do not require a leading . to match dot files
setopt glob_dots

# disable `you have new mail message'
unset MAILCHECK


#
# source any file in etc/sh/rc.d/

for file in "$HOME"/".$USER-sh"/etc/sh/rc.d/*
do
    . "$file"
done


#
# oh-my-zsh

# source powerlevel10k config file if omz theme is powerlevel10k
[ "${ZSH_THEME#*powerlevel10k}" != "$ZSH_THEME" ] && . "$HOME/.$USER-sh/etc/p10k/config.zsh"
