brew install bat
brew install cloc
brew install exa
brew install ffmpeg
brew install hashcat
brew install jq
brew install mas
brew install maven
brew install nmap
brew install shellcheck
brew install tree
brew install youtube-dl
